version: "1.0"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: medusa_admin
      POSTGRES_PASSWORD: 1729
      POSTGRES_DB: medusa_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  medusa-server:
    build: .
    command: npm start
    env_file: .env.server
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis

  medusa-worker:
    build: .
    command: npm start
    env_file: .env.worker
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
